export const SIP_SETTINGS_FIELDS = [
  { label: 'SIP Address of WAN', type: 'select', key: 'sipWan', options: ['Lan 1:192.168.1.101', 'Lan 2:192.168.0.101 '] },
  { label: 'SIP Signaling Port', type: 'text', key: 'sipPort'  },
  { label: 'TLS', type: 'checkbox', key: 'tls',  },
  { label: 'When the externally bound is enabled, only the externally bound address is matched to confirm the SIP trunk:', type: 'checkbox', key: 'externalBound' },
  { label: 'Send 180 before sending 183', type: 'checkbox', key: 'send180'},
  { label: 'Send 183 Message', type: 'checkbox', key: 'send183'  },
  { label: 'Called Number Prefix for 180 Reply (Up to 5 are Allowed, Separated by ":")', type: 'text', key: 'calledPrefix' },
  { label: 'Send 100rel', type: 'checkbox', key: 'send100rel' },
  { label: 'IP Call In First Route', type: 'select', key: 'ipCallRoute', options: ['IP to PSTN', 'IP to IP'] },
  { label: 'Soft-switch to be Connected', type: 'select', key: 'softSwitch', options: ['Others'] },
  { label: 'Hide CallerID', type: 'select', key: 'hideCallerId', options: ['Not Hidden', 'Hidden'] },
  { label: 'Obtain CallerID from', type: 'select', key: 'obtainCallerId', options: ['Username of From Field', 'Displayname of From Feild', 'P-Preferred-Identity Field', 'P-Asserted-Identity Field'] },
  { label: 'Obtain CalleeID from', type: 'select', key: 'obtainCalleeId', options: [" 'To' Field", "'Request' Field"] },
  { label: 'Send CalleeID from', type: 'select', key: 'sendCalleeId', options: ["'To' Field", "'Request' Field"] },
  { label: 'Asserted Identity Mode', type: 'select', key: 'assertedId', options: ['Disable', 'P-Asserted-Identity', 'P-Preferred-Identity'] },
  { label: 'Prack Send Mode', type: 'select', key: 'prackSend', options: ['Disable', 'Supported','Require'] },
  { label: 'DisplayName', type: 'select', key: 'displayName', options: ['Hide', 'Caller']},
  { label: 'UserName', type: 'select', key: 'userName', options: ['Change Caller', 'Caller'] },
  { label: 'Sip Address', type: 'select', key: 'sipAddress', options: ['IPv4', 'IPv6']},
  { label: 'Send/Obtain Redirecting Number/Original CalleeID from Diversion Field', type: 'checkbox', key: 'diversionField'},
  { label: 'NAT Traversal', type: 'checkbox', key: 'natTraversal' },
  { label: 'Set Redirection Parameter of REL Message When Receive Refer Message', type: 'checkbox', key: 'relMessage' },
  { label: 'RTP Self-adaption', type: 'checkbox', key: 'rtpSelf' },
  { label: 'Rport', type: 'checkbox', key: 'rport' },
  { label: 'Filter Out Fake Calls (CallerID is the same as CalleeID)', type: 'checkbox', key: 'filterFake' },
  { label: 'Auto Reply of Source Address', type: 'checkbox', key: 'autoReply'},
  { label: 'Multiple Audio Selection', type: 'select', key: 'audioSelection', options: ['RTP/Audio', 'SIP/Audio'] },
  { label: 'Send Response By Former Via', type: 'checkbox', key: 'responseVia'},
  { label: 'Registration related settings', type: 'checkbox', key: 'registrationSettings', default: false },
  { label: 'Caller Over Clocking(IP OUT)', type: 'checkbox', key: 'callerOverClock' },
  { label: 'Eth Resource', type: 'checkbox', key: 'ethResource' },
  { label: 'SIP Account Numbers', type: 'text', key: 'sipAccountNumbers' },
  { label: 'SIP Account Registration Interval (MS)', type: 'text', key: 'sipAccountInterval' },
  { label: 'DSCP', type: 'checkbox', key: 'dscp' },
  { label: 'Calls from SIP Trunk Address only', type: 'checkbox', key: 'callsFromTrunkOnly' },
  { label: 'Match Call Count to SIP Trunk based on Source Address of INVITE', type: 'checkbox', key: 'matchCallCount' },
  { label: 'Switch Signal Port if SIP Registration Failed', type: 'checkbox', key: 'switchSignalPort' },
  { label: 'Hang up upon Call Time-out', type: 'checkbox', key: 'hangupTimeout'},
  { label: 'Working Period', type: 'checkbox', key: 'workingPeriod', labelAfter: '24 Hours' },
  { label: 'Session Timer', type: 'checkbox', key: 'sessionTimer' },
  { label: 'Media Stream Processing', type: 'checkbox', key: 'mediaStream',},
  { label: 'Sip Trunk Heart', type: 'checkbox', key: 'sipTrunkHeart'},
  { label: 'Early Media', type: 'checkbox', key: 'earlyMedia'},
  { label: 'Early Session', type: 'checkbox', key: 'earlySession' },
  { label: 'Support 100rel', type: 'checkbox', key: 'support100rel' },
  { label: 'Not Wait ACK after Sending 200 OK', type: 'checkbox', key: 'notWaitAck'},
  { label: 'Match Sip Trunk Port', type: 'checkbox', key: 'matchTrunkPort' },
  { label: 'The Percentage of Registration Message Sending Cycle to Period of Validity(%)', type: 'text', key: 'regMsgPercent' },
  { label: 'Maximum Wait Answer Time(s)', type: 'text', key: 'maxWaitAnswer' },
  { label: 'Maximum Wait RTP Time(s)', type: 'text', key: 'maxWaitRtp' },
  { label: 'Maximum Wait PSTN Resource Time(ms)', type: 'text', key: 'maxWaitPstn' },
  { label: 'Switch Network Port by Packet Loss Rate', type: 'checkbox', key: 'switchNetPort' },
  { label: 'Add Content to To Field in INVITE Message', type: 'radio', key: 'addContactTo', options: ['Yes', 'No'] },
  { label: 'UserAgent Field', type: 'text', key: 'userAgent' },
];

export const SIP_SETTINGS_NOTE =
  'Note: Only one SIP Trunk can be configured and it is "Local Network Port" should be set to "Any Lan" once the feature "Switch Network Port by Packet Loss Rate" is enabled.';
