export const SIP_TRUNK_FIELDS = [
  { label: 'Index', key: 'index', type: 'text' },
  { label: 'Description', key: 'description', type: 'text' },
  { label: 'SIP Agent', key: 'sipAgent', type: 'checkbox' },
  { label: 'Username', key: 'username', type: 'text' },
  { label: 'Register Status', key: 'registerStatus', type: 'text' },
  { label: 'Remote Address', key: 'remoteAddress', type: 'text' },
  { label: 'Remote Port', key: 'remotePort', type: 'text' },
  { label: 'Local Network Port', key: 'localNetworkPort', type: 'select', options: ['LAN 1(192.168.1.1)'] },
  { label: 'Local Sip Port', key: 'localSipPort', type: 'select', options: ['5060'] },
  { label: 'Display CODEC', key: 'displayCodec', type: 'checkbox' },
  { label: 'Transport Protocol', key: 'transportProtocol', type: 'select', options: ['UDP'] },
  { label: 'SRTP Mode', key: 'srtpMode', type: 'select', options: ['RTP Prior'] },
  { label: 'Outgoing Voice Resource', key: 'outgoingVoiceResource', type: 'text' },
  { label: 'Incoming Voice Resource', key: 'incomingVoiceResource', type: 'text' },
  { label: 'DTMF Transmit Mode', key: 'dtmfTransmitMode', type: 'select', options: ['Global'] },
  { label: 'Fax Mode', key: 'faxMode', type: 'select', options: ['Global'] },
  { label: 'Working Period', key: 'workingPeriod', type: 'checkbox', labelAfter: '24 Hour' },
  { label: 'VOS1.1 SIP Encryption', key: 'sipEncryption', type: 'select', options: ['No Encryption'] },
  { label: 'VOS1.1 RTP EncryptKey', key: 'rtpEncryptKey', type: 'checkbox' },
  { label: 'Externally Bound Enable', key: 'externallyBoundEnable', type: 'select', options: ['No'] },
];

export const SIP_TRUNK_INITIAL_FORM = {
  index: 0,
  description: 'default',
  sipAgent: false,
  username: '--',
  registerStatus: '--',
  remoteAddress: '',
  remotePort: ' ',
  localNetworkPort: 'LAN 1(192.168.1.1)',
  localSipPort: ' ',
  displayCodec: false,
  transportProtocol: 'UDP',
  srtpMode: 'RTP Prior',
  outgoingVoiceResource: ' ',
  incomingVoiceResource: ' ',
  dtmfTransmitMode: 'Global',
  faxMode: 'Global',
  workingPeriod: false,
  sipEncryption: 'No Encryption',
  rtpEncryptKey: false,
  externallyBoundEnable: 'No',
};
